version: '1'
services:
  db:
    image: postgres:12.2
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    restart: always             # run as a service

  odoo12:
    image: odoo:12.0
    depends_on:
      - db
    ports:
      - "8071:8069"
    tty: true
    command: -- --dev=reload
    volumes:
      - ./addons:./cinema
    restart: always             # run as a service